### PR TITLE
Remove a border for 2022.11

### PR DESCRIPTION
**Pull request by ildar170975**
Removed a border displaying in 2022.11

### CODE REVIEW

**Comment by EuleMitKeule** [comment]
Please merge this, my UI looks really bad with all those borders right now. 😅

**Comment by EuleMitKeule** [comment]
@thomasloven Is this repo still maintained? I bet tons of people experience this ugly border bug and this is a quick and easy fix would it be merged.

**Comment by ildar170975** [comment]
> experience this ugly border bug

Technically, this is not card-mod's bug. This is an incompatibility with a changed HA, consequences of ill-conceived decision in HA design.

**Comment by EuleMitKeule** [comment]
@ildar170975 I absolutely agree. Still some help from the maintainer would be much appreciated!
Could you by any chance tell me, how I could fix this in my configuration until this PR is merged? Do I have to fork card-mod and build a fixed version or is there a simpler way?

**Comment by ildar170975** [comment]
Try applying this style for mod-card:
```
  ha-card {
    border: none;
  }
```

**Comment by EuleMitKeule** [comment]
@ildar170975 I just noticed, I'm actually not using any mod-cards. This seems to happen for every button-card I use, so it's not caused by card-mod at all. I will check the button-card repo for a fix. Apparently card-mod is not the only plugin experiencing this issue.

**Comment by EuleMitKeule** [comment]
Putting this `ha-card-border-width: 0` into your theme file fixes the issue.

**Comment by ildar170975** [comment]
> Putting this `ha-card-border-width: 0` into your theme file fixes the issue.

[Not exactly](https://github.com/thomasloven/lovelace-card-mod/issues/230#issuecomment-1319917940)

**Comment by PeteCooney** [comment]
As a temporary workaround, until this pull request gets approved, it's possible to manually add this change to the card-mod.js file. Note though that you'll also want to update the card-mod.js.gz compressed version as well or some (all?) browsers won't actually pick up the change. Also ensure that you clear your browser cache after making the change.

Standard disclaimer: I accept no responsibility if you break anything by manually editing these (or any other) files.

**Pull request merged**
